version: '3.8'

services:
  # db:
  #   image: mysql/mysql-server:8.0
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'investment-managing'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - '3308:3306'
  # db-integration-test:
  #   image: mysql/mysql-server:8.0
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'investment_managing_integration_test'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - '3309:3306'
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'investment-managing'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-e2e:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'investment_managing_integration_test'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_e2e:/var/lib/postgresql/data
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "teste123"
    ports:
      - "16543:80"

volumes:
  postgres_data:
  postgres_data_e2e:
