export default {
  'BUY_S&P500_1': {
    generalInformation: {
      brokerageOrderNumber: 75670314,
      tradingFlorDate: '2023-10-20',
      clientId: '2079101',
    },
    orders: [
      {
        market: 'BOVESPA',
        buyOrSell: 'BUY',
        marketType: 'VISTA',
        symbol: 'S&P500',
        quantity: 22,
        price: 236.45,
        total: 5201.9,
        debitOrCredit: 'DEBIT',
      },
    ],
    businessSummary: {
      debentures: 0.0,
      sellInCash: 0.0,
      buyInCash: 5201.9,
      optionsBuy: 0.0,
      optionsSell: 0.0,
      termOptions: 0.0,
      federalSecurities: 0.0,
      operationValues: 5201.9,
    },
    financialSummary: {
      clearing: {
        operationsNetValue: 5201.9,
        settlementFee: 1.3,
        registryFee: 0.0,
        totalCblc: 5203.2,
      },
      exchange: {
        termOrOptionsFee: 0.0,
        anaFee: 0.0,
        fees: 0.26,
        total: 0.26,
      },
      operationalCosts: {
        operationalFee: 4.9,
        execution: 0.0,
        custody: 0.0,
        taxes: 0.52,
        irrf: 0.0,
        others: 0.28,
        totalCosts: 5.7,
      },
      netDate: '2023-10-24',
      netTotalValue: 5209.16,
      netDebitOrCredit: 'DEBIT',
    },
  },
  'BUY_S&P500_2': {
    generalInformation: {
      brokerageOrderNumber: 75967773,
      tradingFlorDate: '2023-10-26',
      clientId: '2079101',
    },
    orders: [
      {
        market: 'BOVESPA',
        buyOrSell: 'BUY',
        marketType: 'VISTA',
        symbol: 'S&P500',
        quantity: 5,
        price: 231.43,
        total: 1157.15,
        debitOrCredit: 'DEBIT',
      },
    ],
    businessSummary: {
      debentures: 0.0,
      sellInCash: 0.0,
      buyInCash: 1157.15,
      optionsBuy: 0.0,
      optionsSell: 0.0,
      termOptions: 0.0,
      federalSecurities: 0.0,
      operationValues: 1157.15,
    },
    financialSummary: {
      clearing: {
        operationsNetValue: 1157.15,
        settlementFee: 0.28,
        registryFee: 0.0,
        totalCblc: 1157.43,
      },
      exchange: {
        termOrOptionsFee: 0.0,
        anaFee: 0.0,
        fees: 0.05,
        total: 0.05,
      },
      operationalCosts: {
        operationalFee: 4.9,
        execution: 0.0,
        custody: 0.0,
        taxes: 0.52,
        irrf: 0.0,
        others: 0.28,
        totalCosts: 1163.18,
      },
      netDate: '2023-10-24',
      netTotalValue: 5209.16,
      netDebitOrCredit: 'DEBIT',
    },
  },
  'SELL_S&P500_1': {
    generalInformation: {
      brokerageOrderNumber: 75967774,
      tradingFlorDate: '2023-10-28',
      clientId: '2079101',
    },
    orders: [
      {
        market: 'BOVESPA',
        buyOrSell: 'SELL',
        marketType: 'VISTA',
        symbol: 'S&P500',
        quantity: 5,
        price: 225.53,
        total: 1127.65,
        debitOrCredit: 'CREDIT',
      },
    ],
    businessSummary: {
      debentures: 0.0,
      sellInCash: 1127.65,
      buyInCash: 0.0,
      optionsBuy: 0.0,
      optionsSell: 0.0,
      termOptions: 0.0,
      federalSecurities: 0.0,
      operationValues: 1127.65,
    },
    financialSummary: {
      clearing: {
        operationsNetValue: 1127.65,
        settlementFee: 0.28,
        registryFee: 0.0,
        totalCblc: 1127.93,
      },
      exchange: {
        termOrOptionsFee: 0.0,
        anaFee: 0.0,
        fees: 0.05,
        total: 0.05,
      },
      operationalCosts: {
        operationalFee: 4.9,
        execution: 0.0,
        custody: 0.0,
        taxes: 0.52,
        irrf: 0.0,
        others: 0.28,
        totalCosts: 1133.35,
      },
      netDate: '2023-10-24',
      netTotalValue: 1129.23,
      netDebitOrCredit: 'CREDIT',
    },
  },
  BUY_ITUB4_1: {
    generalInformation: {
      brokerageOrderNumber: 75967775,
      tradingFlorDate: '2023-11-10',
      clientId: '2079101',
    },
    orders: [
      {
        market: 'BOVESPA',
        buyOrSell: 'BUY',
        marketType: 'VISTA',
        symbol: 'ITUB4',
        quantity: 100,
        price: 24.3,
        total: 2430.0,
        debitOrCredit: 'DEBIT',
      },
    ],
    businessSummary: {
      debentures: 0.0,
      sellInCash: 0.0,
      buyInCash: 2430.0,
      optionsBuy: 0.0,
      optionsSell: 0.0,
      termOptions: 0.0,
      federalSecurities: 0.0,
      operationValues: 2430.0,
    },
    financialSummary: {
      clearing: {
        operationsNetValue: 2430.0,
        settlementFee: 0.28,
        registryFee: 0.0,
        totalCblc: 2430.28,
      },
      exchange: {
        termOrOptionsFee: 0.0,
        anaFee: 0.0,
        fees: 0.05,
        total: 0.05,
      },
      operationalCosts: {
        operationalFee: 4.9,
        execution: 0.0,
        custody: 0.0,
        taxes: 0.52,
        irrf: 0.0,
        others: 0.28,
        totalCosts: 2433.11,
      },
      netDate: '2023-11-10',
      netTotalValue: 2433.11,
      netDebitOrCredit: 'DEBIT',
    },
  },
};
